def steel_to_carbon_steel(String oredict, ItemStack item) {
    ore_dict.remove(oredict + "Steel", item)
    ore_dict.add(oredict + "CarbonSteel", item) 
}

steel_to_carbon_steel("block", item("immersiveengineering:storage:8"))
//crafting.removeByOutput(item("immersiveengineering:storage:8"))
crafting.shapedBuilder()
    .name("carbon_steel_ingot_compacting")
    .output(item("immersiveengineering:storage:8"))
    .row("III")
    .row("III")
    .row("III")
    .key("I", item("immersiveengineering:metal:8"))
    .register()

steel_to_carbon_steel("ingot", item("immersiveengineering:metal:8"))
//crafting.removeByOutput(item("immersiveengineering:metal:8"))
crafting.shapedBuilder()
    .name("carbon_steel_nugget_compacting")
    .output(item("immersiveengineering:metal:8"))
    .row("III")
    .row("III")
    .row("III")
    .key("I", item("immersiveengineering:metal:28"))
    .register()
crafting.shapelessBuilder()
    .name("carbon_steel_block_expanding")
    .output(item("immersiveengineering:metal:8").multiply(9))
    .input(item("immersiveengineering:storage:8"))
    .register()

steel_to_carbon_steel("nugget", item("immersiveengineering:metal:28"))
//crafting.removeByOutput(item("immersiveengineering:metal:28"))
crafting.shapelessBuilder()
    .name("carbon_steel_ingot_expanding")
    .output(item("immersiveengineering:metal:28").multiply(9))
    .input(item("immersiveengineering:metal:8"))
    .register()

steel_to_carbon_steel("slab", item("immersiveengineering:storage_slab:8"))
steel_to_carbon_steel("blockSheetmetal", item("immersiveengineering:sheetmetal:8"))
steel_to_carbon_steel("slabSheetmetal", item("immersiveengineering:sheetmetal_slab:8"))
steel_to_carbon_steel("fence", item("immersiveengineering:metal_decoration1"))
steel_to_carbon_steel("scaffolding", item("immersiveengineering:metal_decoration1:1"))
crafting.removeByOutput(item("immersiveengineering:metal_decoration1:1"))
crafting.shapedBuilder()
    .name("carbon_steel_scaffolding")
    .output(item("immersiveengineering:metal_decoration1:1"))
    .row("III")
    .row(" R ")
    .row("R R")
    .key("R", item("immersiveengineering:material:2"))
    .key("I", item("immersiveengineering:metal:8"))
    .register()

steel_to_carbon_steel("scaffolding", item("immersiveengineering:metal_decoration1:2"))
steel_to_carbon_steel("scaffolding", item("immersiveengineering:metal_decoration1:3"))

crafting.shapedBuilder()
    .name("steel_post")
    .output(item("immersiveengineering:metal_decoration2"))
    .row(" R ")
    .row(" R ")
    .row(" I ")
    .key("R", item("immersiveengineering:material:2"))
    .key("I", item("immersiveengineering:metal:8"))
    .register()




