mods.astralsorcery.starlight_altar.removeByOutput(item("astralsorcery:blockblackmarble"))
mods.astralsorcery.starlight_altar.discoveryRecipeBuilder()
    .name("sooty_marble")
    .output(item("astralsorcery:blockblackmarble")*8)
    .row('MMM')
    .row('MCM')
    .row('MMM')
    .key('M', ore("blockMarble"))
    .key("C", item("emergentengineering:crafting_catalyst"))
    .starlight(500)
    .craftTime(10)
    .register()

crafting.removeByOutput(item("thermalexpansion:machine:4"))
mods.astralsorcery.starlight_altar.discoveryRecipeBuilder()
    .name("phytogenic_insulator_skip")
    .output(item("thermalexpansion:machine:4"))
    .row("SWS")
    .row("PFP")
    .row("SWS")
    .key("S", item("emergentengineering:starlight_steel_ingot"))
    .key("W", ore("wireCopper"))
    .key("P", item("thermalfoundation:fertilizer"))
    .key("F", item("emergentengineering:floral_catalyst"))
    .starlight(500)
    .craftTime(600)
    .register()