mods.astralsorcery.starlight_altar.removeByOutput(item("astralsorcery:blockblackmarble"))
mods.astralsorcery.starlight_altar.discoveryRecipeBuilder()
    .name("sooty_marble")
    .output(item("astralsorcery:blockblackmarble")*8)
    .row('MMM')
    .row('MCM')
    .row('MMM')
    .key('M', ore("blockMarble"))
    .key("C", item("emergentengineering:crafting_catalyst"))
    .starlight(500)
    .craftTime(10)
    .register()