log.info("Running alloy_kiln_recipes.groovy!")

mods.ie.alloy_kiln.recipeBuilder()
    .name("coke_brick_charcoal")
    .input([item("minecraft:brick")*2,item("thermalfoundation:material:769")])
    .output(item("emergentengineering:coke_brick")*2)
    .time(200)
    .register()

mods.ie.alloy_kiln.recipeBuilder()
    .name("coke_brick_coal")
    .input([item("minecraft:brick")*4,item("thermalfoundation:material:768")])
    .output(item("emergentengineering:coke_brick")*4)
    .time(200)
    .register()

mods.ie.alloy_kiln.recipeBuilder()
    .name("coke_brick_red_coal")
    .input([item("minecraft:brick")*8,item("emergentengineering:red_coal_dust")])
    .output(item("emergentengineering:coke_brick")*8)
    .time(200)
    .register()

furnace.removeByOutput(item("tconstruct:materials:0"))
mods.ie.alloy_kiln.recipeBuilder()
    .name("seared_brick")
    .input([item("emergentengineering:sandy_clay_blend"),item("minecraft:gravel")])
    .output(item("tconstruct:materials:0")*2)
    .time(100)
    .register()

mods.ie.alloy_kiln.recipeBuilder()
    .name("brick_good")
    .input([item("minecraft:clay"),item("minecraft:sand")])
    .output(item("minecraft:brick")*4)
    .time(100)
    .register()

mods.ie.alloy_kiln.recipeBuilder()
    .name("fire_brick")
    .input([item("emergentengineering:unfired_fire_brick")*4,ore("dustCoke")])
    .output(item("emergentengineering:fire_brick")*4)
    .time(1250)
    .register()

mods.ie.alloy_kiln.recipeBuilder()
    .name("blast_brick")
    .input(item("emergentengineering:fire_brick")*4,item("emergentengineering:blazing_powder"))
    .output(item("emergentengineering:blast_brick")*4)
    .time(500)
    .register()