
crafting.removeByOutput(item("immersiveengineering:material:8"))
mods.ie.blueprint_crafting.removeByOutput("components", item("immersiveengineering:material:8"))
mods.ie.blueprint_crafting.recipeBuilder()
    .name("iron_component_basic")
    .input([ore("plateIron"),ore("plateIron"),ore("stickIron"),ore("gearBronze")])
    .output(item("immersiveengineering:material:8"))
    .category("basic")
    .register()

mods.ie.blueprint_crafting.recipeBuilder()
    .name("iron_component_basic")
    .input([ore("plateIron"),ore("plateBronze")])
    .output(item("immersiveengineering:material:8"))
    .category("advanced")
    .register()

crafting.removeByOutput(item("immersiveengineering:material:9"))
mods.ie.blueprint_crafting.removeByOutput("components", item("immersiveengineering:material:9"))
mods.ie.blueprint_crafting.recipeBuilder()
    .name("carbon_steel_component_basic")
    .input([ore("plateCarbonSteel"),ore("plateCarbonSteel"),ore("stickCarbonSteel"),ore("gearBronze")])
    .output(item("immersiveengineering:material:9"))
    .category("basic")
    .register()

mods.ie.blueprint_crafting.recipeBuilder()
    .name("carbon_steel_component_basic")
    .input([ore("plateCarbonSteel"),ore("plateBronze")])
    .output(item("immersiveengineering:material:9"))
    .category("advanced")
    .register()

crafting.remove("immersiveengineering:sheetmetal/steel_sheetmetal")
mods.ie.blueprint_crafting.recipeBuilder()
    .name("carbon_steel_component_basic")
    .input([ore("plateCarbonSteel"),ore("plateCarbonSteel")])
    .output(item("immersiveengineering:sheetmetal:8"))
    .category("basic")
    .register()

mods.ie.blueprint_crafting.recipeBuilder()
    .name("carbon_steel_component_basic")
    .input([ore("plateCarbonSteel")])
    .output(item("immersiveengineering:sheetmetal:8"))
    .category("advanced")
    .register()