
crafting.removeByOutput(item("immersiveengineering:material:8"))
mods.ie.blueprint_crafting.removeByOutput("components", item("immersiveengineering:material:8"))
mods.ie.blueprint_crafting.recipeBuilder()
    .name("iron_component_expensive")
    .input([ore("plateIron"),ore("plateIron"),ore("stickIron"),ore("gearElectrum")])
    .output(item("immersiveengineering:material:8"))
    .category("basic")
    .register()

mods.ie.blueprint_crafting.recipeBuilder()
    .name("iron_component_basic")
    .input([ore("plateIron"),ore("plateIron"),ore("stickIron"),ore("gearBronze")])
    .output(item("immersiveengineering:material:8"))
    .category("basic")
    .register()

mods.ie.blueprint_crafting.recipeBuilder()
    .name("iron_component_advanced")
    .input([ore("plateIron"),ore("plateBronze")])
    .output(item("immersiveengineering:material:8"))
    .category("advanced")
    .register()

crafting.removeByOutput(item("immersiveengineering:material:9"))
mods.ie.blueprint_crafting.removeByOutput("components", item("immersiveengineering:material:9"))
mods.ie.blueprint_crafting.recipeBuilder()
    .name("carbon_steel_component_expensive")
    .input([ore("plateCarbonSteel"),ore("plateCarbonSteel"),ore("stickCarbonSteel"),ore("gearElectrum")])
    .output(item("immersiveengineering:material:9"))
    .category("basic")
    .register()

mods.ie.blueprint_crafting.recipeBuilder()
    .name("carbon_steel_component_basic")
    .input([ore("plateCarbonSteel"),ore("plateCarbonSteel"),ore("stickCarbonSteel"),ore("gearBronze")])
    .output(item("immersiveengineering:material:9"))
    .category("basic")
    .register()

mods.ie.blueprint_crafting.recipeBuilder()
    .name("carbon_steel_component_advanced")
    .input([ore("plateCarbonSteel"),ore("plateBronze")])
    .output(item("immersiveengineering:material:9"))
    .category("advanced")
    .register()

crafting.remove("immersiveengineering:sheetmetal/steel_sheetmetal")
mods.ie.blueprint_crafting.recipeBuilder()
    .name("carbon_steel_sheetmetal_basic")
    .input([ore("plateCarbonSteel")]*2+[item("immersiveengineering:tool")])
    .output(item("immersiveengineering:sheetmetal:8"))
    .category("basic")
    .register()

mods.ie.blueprint_crafting.recipeBuilder()
    .name("carbon_steel_sheetmetal_advanced")
    .input([ore("plateCarbonSteel"),item("immersiveengineering:tool")])
    .output(item("immersiveengineering:sheetmetal:8"))
    .category("advanced")
    .register()

crafting.remove("immersiveengineering:sheetmetal/iron_sheetmetal")
mods.ie.blueprint_crafting.recipeBuilder()
    .name("iron_sheetmetal_basic")
    .input([ore("plateIron")]*2+[item("immersiveengineering:tool")])
    .output(item("immersiveengineering:sheetmetal:9"))
    .category("basic")
    .register()

mods.ie.blueprint_crafting.recipeBuilder()
    .name("iron_sheetmetal_advanced")
    .input([ore("plateIron"),item("immersiveengineering:tool")])
    .output(item("immersiveengineering:sheetmetal:9"))
    .category("advanced")
    .register()

mods.ie.blueprint_crafting.recipeBuilder()
    .name("metal_press_mold_base")
    .input([ore("plateCarbonSteel")]*6+[item("immersiveengineering:tool")])
    .output(item("emergentengineering:metal_press_mold_base"))
    .category("molds")
    .register()

mods.ie.blueprint_crafting.removeByOutput("molds",item("immersiveengineering:mold:0"))
mods.ie.blueprint_crafting.recipeBuilder()
    .name("metal_press_mold_0")
    .input([item("emergentengineering:metal_press_mold_base"),ore("plateElectrum"),item("immersiveengineering:tool:1")])
    .output(item("immersiveengineering:mold:0"))
    .category("molds")
    .register()

mods.ie.blueprint_crafting.removeByOutput("molds",item("immersiveengineering:mold:1"))
mods.ie.blueprint_crafting.recipeBuilder()
    .name("metal_press_mold_1")
    .input([item("emergentengineering:metal_press_mold_base"),ore("gearElectrum"),item("immersiveengineering:tool:1")])
    .output(item("immersiveengineering:mold:1"))
    .category("molds")
    .register()

mods.ie.blueprint_crafting.removeByOutput("molds",item("immersiveengineering:mold:2"))
mods.ie.blueprint_crafting.recipeBuilder()
    .name("metal_press_mold_2")
    .input([item("emergentengineering:metal_press_mold_base"),ore("stickElectrum"),item("immersiveengineering:tool:1")])
    .output(item("immersiveengineering:mold:2"))
    .category("molds")
    .register()

mods.ie.blueprint_crafting.removeByOutput("molds",item("immersiveengineering:mold:4"))
mods.ie.blueprint_crafting.recipeBuilder()
    .name("metal_press_mold_4")
    .input([item("emergentengineering:metal_press_mold_base"),ore("wireElectrum"),item("immersiveengineering:tool:1")])
    .output(item("immersiveengineering:mold:4"))
    .category("molds")
    .register()

mods.ie.blueprint_crafting.removeByOutput("molds",item("immersiveengineering:mold:3"))
mods.ie.blueprint_crafting.recipeBuilder()
    .name("metal_press_mold_3")
    .input([item("emergentengineering:metal_press_mold_base"),item("immersiveengineering:tool:1")])
    .output(item("immersiveengineering:mold:3"))
    .category("molds")
    .register()

mods.ie.blueprint_crafting.removeByOutput("molds",item("immersiveengineering:mold:5"))
mods.ie.blueprint_crafting.recipeBuilder()
    .name("metal_press_mold_5")
    .input([item("emergentengineering:metal_press_mold_base"),item("immersiveengineering:tool:1")])
    .output(item("immersiveengineering:mold:5"))
    .category("molds")
    .register()

mods.ie.blueprint_crafting.removeByOutput("molds",item("immersiveengineering:mold:6"))
mods.ie.blueprint_crafting.recipeBuilder()
    .name("metal_press_mold_6")
    .input([item("emergentengineering:metal_press_mold_base"),item("immersiveengineering:tool:1")])
    .output(item("immersiveengineering:mold:6"))
    .category("molds")
    .register()

mods.ie.blueprint_crafting.removeByOutput("molds",item("immersiveengineering:mold:7"))
mods.ie.blueprint_crafting.recipeBuilder()
    .name("metal_press_mold_7")
    .input([item("emergentengineering:metal_press_mold_base"),item("immersiveengineering:tool:1")])
    .output(item("immersiveengineering:mold:7"))
    .category("molds")
    .register()