mods.ie.alloy_kiln.recipeBuilder()
    .name("coke_brick_coal")
    .input([item("minecraft:brick").multiply(4),item("thermalfoundation:material:768")])
    .output(item("emergentengineering:coke_brick").multiply(4))
    .time(200)
    .register()

mods.ie.alloy_kiln.recipeBuilder()
    .name("coke_brick_charcoal")
    .input([item("minecraft:brick").multiply(2),item("thermalfoundation:material:769")])
    .output(item("emergentengineering:coke_brick").multiply(2))
    .time(200)
    .register()

furnace.removeByOutput(item("tconstruct:materials:0"))
mods.ie.alloy_kiln.recipeBuilder()
    .name("seared_brick")
    .input([item("emergentengineering:sandy_clay_blend"),item("minecraft:gravel")])
    .output(item("tconstruct:materials:0").multiply(2))
    .time(100)
    .register()

mods.ie.alloy_kiln.recipeBuilder()
    .name("brick_good")
    .input([item("minecraft:clay"),item("minecraft:sand")])
    .output(item("minecraft:brick").multiply(4))
    .time(100)
    .register()