in_world_crafting.fluid_to_item.recipeBuilder()
    .name("marine_clay_iw")
    .input(item("minecraft:sand"))
    .fluidInput(fluid("water"))
    .output(item("emergentengineering:marine_clay"))
    .register()

in_world_crafting.burning.recipeBuilder()
    .input(item('minecraft:netherrack'))
    .output(item('minecraft:nether_star'))
    .register()

in_world_crafting.burning.recipeBuilder()
    .name("blazing_blend_iw")
    .input(item("emergentengineering:nethengenic_blend"))
    .output(item("emergentengineering:blazing_powder"))
    .register()

mods.tconstruct.drying.recipeBuilder()
    .name("drying_marine_clay")
    .input(item("emergentengineering:marine_clay"))
    .output(item("minecraft:clay_ball"))
    .time(600)
    .register()

mods.extrautils2.resonator.recipeBuilder()
    .name("resonating_redstone_crystal")
    .input(item("minecraft:redstone_block"))
    .output(item("extrautils2:ingredients"))
    .energy(3200)
    .register()

mods.appliedenergistics2.grinder.removeAll()
crafting.removeByOutput(item("appliedenergistics2:grindstone"))