crafting.shapelessBuilder()
    .name("sandy_clay_blend")
    .output(item("emergentengineering:sandy_clay_blend"))
    .input([item("minecraft:clay_ball"),item("minecraft:sand")])
    .register()

crafting.shapelessBuilder()
    .name("heat_resistant_clay_blend")
    .input([item("minecraft:clay_ball"),ore("dustQuartz"),ore("dustAluminum"),ore("dustCharcoal")])
    .output(item("emergentengineering:heat_resistant_clay_blend"))
    .register()

crafting.shapelessBuilder()
    .name("heat_resistant_clay_blend_certus")
    .input([item("minecraft:clay_ball"),ore("dustCertusQuartz"),ore("dustAluminum"),ore("dustCharcoal")])
    .output(item("emergentengineering:heat_resistant_clay_blend"))
    .register()

crafting.removeByOutput(item("extrautils2:ingredients"))
crafting.shapelessBuilder()
    .name("resonating_redstone_crystal_from_ore")
    .input([item("minecraft:redstone_ore"),item("minecraft:ender_pearl")])
    .output(item("extrautils2:ingredients"))
    .register()

crafting.shapelessBuilder()
    .name("blazing_blend_x1")
    .input([ore("dustSulfur"), item("minecraft:gunpowder"), item("minecraft:redstone")])
    .output(item("emergentengineering:nethengenic_blend"))
    .register()

crafting.shapelessBuilder()
    .name("blazing_blend_resonating")
    .input([ore("dustSulfur"), item("minecraft:gunpowder"), item("extrautils2:ingredients")])
    .output(item("emergentengineering:nethengenic_blend")*2)
    .register()

crafting.shapelessBuilder()
    .name("blazing_blend_red_coal")
    .input([ore("dustSulfur"), item("minecraft:gunpowder"), item("emergentengineering:red_coal_dust"), item("minecraft:redstone")])
    .output(item("emergentengineering:nethengenic_blend")*2)
    .register()

crafting.shapelessBuilder()
    .name("blazing_blend_resonating_red_coal")
    .input([ore("dustSulfur"), item("minecraft:gunpowder"), item("emergentengineering:red_coal_dust"), item("extrautils2:ingredients")])
    .output(item("emergentengineering:nethengenic_blend")*4)
    .register()

crafting.remove("immersiveengineering:material/gunpowder0")
crafting.remove("immersiveengineering:material/gunpowder1")
crafting.remove("thermalfoundation:gunpowder")
crafting.remove("thermalfoundation:gunpowder_1")
crafting.shapelessBuilder()
    .name("gunpowderx1")
    .input([ore("dustSaltpeter"),ore("dustSaltpeter"),ore("dustSaltpeter"),ore("dustSaltpeter"),
    ore("dustSulfur"),ore("dustCoal")])
    .output(item("minecraft:gunpowder"))
    .register()

crafting.shapelessBuilder()
    .name("gunpowderx2")
    .input([ore("dustSaltpeter"),ore("dustSaltpeter"),ore("dustSaltpeter"),ore("dustSaltpeter"),
    ore("dustSulfur"),ore("dustCharcoal")])
    .output(item("minecraft:gunpowder")*2)
    .register()

crafting.shapelessBuilder()
    .name("gunpowderx4")
    .input([ore("dustSaltpeter"),ore("dustSaltpeter"),ore("dustSaltpeter"),ore("dustSaltpeter"),
    ore("dustSulfur"),item("emergentengineering:red_coal_dust")])
    .output(item("minecraft:gunpowder")*4)
    .register()

crafting.removeByOutput(item("immersiveengineering:blueprint").withNbt([blueprint: "molds"]))
crafting.shapelessBuilder()
    .name("blueprint_metal_press")
    .input([item("immersiveengineering:blueprint").withNbt([blueprint: "blank"]),ore("plateCarbonSteel")])
    .output(item("immersiveengineering:blueprint").withNbt([blueprint: "molds"]))
    .register()

crafting.removeByOutput(item("immersiveengineering:blueprint").withNbt([blueprint: "components"]))
crafting.shapelessBuilder()
    .name("blueprint_components")
    .input([item("immersiveengineering:blueprint").withNbt([blueprint: "blank"]),ore("plateBronze"),ore("plateElectrum"),ore("plateCarbonSteel")])
    .output(item("immersiveengineering:blueprint").withNbt([blueprint: "components"]))
    .register()

crafting.removeByOutput(item("immersiveengineering:blueprint").withNbt([blueprint: "bullet"]))
crafting.shapelessBuilder()
    .name("blueprint_bullet")
    .input([item("immersiveengineering:blueprint").withNbt([blueprint: "blank"]),ore("gunpowder"),ore("plateElectrum"),ore("gunpowder")])
    .output(item("immersiveengineering:blueprint").withNbt([blueprint: "bullet"]))
    .register()

//mods.jei.ingredient.add(item("immersiveengineering:blueprint").withNbt([blueprint: "basic"))
crafting.shapelessBuilder()
    .name("blueprint_basic")
    .input([item("immersiveengineering:blueprint").withNbt([blueprint: "blank"]),item("immersiveengineering:tool")])
    .output(item("immersiveengineering:blueprint").withNbt([blueprint: "basic"]))
    .register()

crafting.remove("immersiveengineering:stone_decoration/blastbrick_reinforced")
crafting.shapelessBuilder()
    .name("reinforce_blast_brick")
    .input([item("immersiveengineering:stone_decoration:1"),ore("plateCarbonSteel")])
    .output(item("immersiveengineering:stone_decoration:2"))
    .register()

crafting.shapelessBuilder()
    .name("ferrous_juniper_sapling")
    .input([ore("treeSapling"),item("extrautils2:ironwood_log")])
    .output(item("extrautils2:ironwood_sapling"))
    .register()

crafting.shapelessBuilder()
    .name("ferrous_juniper_sapling_dcc")
    .input([ore("treeSapling"),item("avaritia:double_compressed_crafting_table")])
    .output(item("extrautils2:ironwood_sapling"))
    .register()

crafting.removeByOutput(item("astralsorcery:blockblackmarble"))
crafting.shapelessBuilder()
    .name("sooty_marble_1")
    .input([item("emergentengineering:double_compressed_marble"),ore("dustCoal").or(ore("dustCharcoal"))])
    .output(item("astralsorcery:blockblackmarble"))
    .register()

crafting.shapelessBuilder()
    .name("sooty_marble_2")
    .input([item("emergentengineering:compressed_marble")]*5+[item("emergentengineering:red_coal_dust")])
    .output(item("astralsorcery:blockblackmarble"))
    .register()

crafting.shapelessBuilder()
    .name("sooty_marble_3")
    .input([item("emergentengineering:compressed_marble"),item("emergentengineering:crafting_catalyst")])
    .output(item("astralsorcery:blockblackmarble"))
    .register()