import classes.recipe

crafting.removeByOutput(item("tconstruct:rack:1"))
crafting.shapedBuilder()
    .name("gated_drying_rack")
    .output(item("tconstruct:rack:1"))
    .row("SSS")
    .row("N N")
    .key("S", item("minecraft:wooden_slab"))
    .key("N", item("thermalfoundation:material:227"))
    .register()

crafting.removeByOutput(item("extrautils2:machine"))
crafting.shapedBuilder()
    .name("gated_expensive_machine_block")
    .output(item("extrautils2:machine"))
    .row("CRC")
    .row("RER")
    .row("CRC")
    .key("C",item("immersiveengineering:material:9"))
    .key("R",item("minecraft:redstone_block"))
    .key("E",item("immersiveengineering:metal_decoration0:3"))
    .register()

crafting.shapedBuilder()
    .name("gated_machine_block")
    .output(item("extrautils2:machine")*2)
    .row("CRC")
    .row("RER")
    .row("CRC")
    .key("C",item("immersiveengineering:material:9"))
    .key("R",item("extrautils2:ingredients"))
    .key("E",item("immersiveengineering:metal_decoration0:3"))
    .register()

crafting.removeByOutput(item("immersiveengineering:metal_decoration0:3"))
crafting.shapedBuilder()
    .name("expensive_redstone_eb")
    .output(item("immersiveengineering:metal_decoration0:3"))
    .row("CRC")
    .row("RER")
    .row("CRC")
    .key("C",item("immersiveengineering:material:8"))
    .key("R",item("minecraft:redstone_block"))
    .key("E",item("immersiveengineering:metal_decoration0"))
    .register()

crafting.shapedBuilder()
    .name("redstone_eb")
    .output(item("immersiveengineering:metal_decoration0:3")*2)
    .row("CRC")
    .row("RER")
    .row("CRC")
    .key("C",ore("blockSheetmetalIron"))
    .key("R",item("extrautils2:ingredients"))
    .key("E",item("immersiveengineering:metal_decoration0"))
    .register()

crafting.removeByOutput(item("immersiveengineering:metal_decoration0:4"))
crafting.shapedBuilder()
    .name("light_eb")
    .output(item("immersiveengineering:metal_decoration0:4"))
    .row("SCS")
    .row("PGP")
    .row("SCS")
    .key("S",ore("blockSheetmetalIron"))
    .key("C",item("immersiveengineering:material:8"))
    .key("P",ore("plateBronze"))
    .key("G",ore("gearBronze"))
    .register()

crafting.removeByOutput(item("immersiveengineering:metal_decoration0:5"))
crafting.shapedBuilder()
    .name("heavy_eb")
    .output(item("immersiveengineering:metal_decoration0:5"))
    .row("SCS")
    .row("PGP")
    .row("SCS")
    .key("S", ore("blockSheetmetalCarbonSteel"))
    .key("C",item("immersiveengineering:material:9"))
    .key("P",item("minecraft:piston"))
    .key("G",ore("gearElectrum"))
    .register()

crafting.removeByOutput(item("minecraft:piston"))
crafting.shapedBuilder()
    .name("expensive_piston")
    .output(item("minecraft:piston"))
    .row("WWW")
    .row("CPC")
    .row("CRC")
    .key("W",ore("plankWood"))
    .key("C",ore("compressed1xCobblestone"))
    .key("P",ore("plateCarbonSteel"))
    .key("R",ore("blockRedstone"))
    .register()

crafting.shapedBuilder()
    .name("piston")
    .output(item("minecraft:piston"))
    .row("WWW")
    .row("CPC")
    .row("CRC")
    .key("W",ore("plankWood"))
    .key("C",ore("cobblestone"))
    .key("P",ore("plateCarbonSteel"))
    .key("R",item("extrautils2:ingredients"))
    .register()

//mods.jei.ingredient.add(item("immersiveengineering:blueprint").withNbt([blueprint: "blank"))
crafting.shapedBuilder()
    .name("blank_engineers_blueprint")
    .output(item("immersiveengineering:blueprint").withNbt([blueprint: "blank"]))
    .row("GGG")
    .row("LLL")
    .row("PPP")
    .key("G",item("minecraft:gunpowder"))
    .key("L",ore("dyeBlue"))
    .key("P",ore("paper"))
    .register()

crafting.removeByOutput(item("immersiveengineering:material:10"))
crafting.shapedBuilder()
    .name("waterwheel_segment")
    .output(item("immersiveengineering:material:10"))
    .row(" S ")
    .row("SSS")
    .row("PRP")
    .key("S", ore("stickTreatedWood"))
    .key("P", ore("plankTreatedWood"))
    .key("R", ore("stickCarbonSteel"))
    .register()

crafting.removeByOutput(item("immersiveengineering:wooden_device1"))
crafting.shapedBuilder()
    .name("waterwheel")
    .output(item("immersiveengineering:wooden_device1"))
    .row("SSS")
    .row("SGS")
    .row("SSS")
    .key("S", item("immersiveengineering:material:10"))
    .key("G", ore("gearCarbonSteel"))
    .register()

crafting.removeByOutput(item("immersiveengineering:metal_device1:1"))
crafting.shapedBuilder()
    .name("external_heater_expensive")
    .output(item("immersiveengineering:metal_device1:1"))
    .row("SBS")
    .row("BCB")
    .row("SRS")
    .key("S", ore("blockSheetmetalIron"))
    .key("B", item("immersiveengineering:stone_decoration"))
    .key("C", item("immersiveengineering:metal_decoration0"))
    .key("R", item("minecraft:redstone_block"))
    .register()

crafting.shapedBuilder()
    .name("external_heater")
    .output(item("immersiveengineering:metal_device1:1")*2)
    .row("SBS")
    .row("BCB")
    .row("SRS")
    .key("S", ore("blockSheetmetalIron"))
    .key("B", item("immersiveengineering:stone_decoration"))
    .key("C", item("immersiveengineering:metal_decoration0"))
    .key("R", item("extrautils2:ingredients"))
    .register()

crafting.removeByOutput(item("astralsorcery:blockaltar"))
crafting.shapedBuilder()
    .name("luminous_crafting_table")
    .output(item("astralsorcery:blockaltar"))
    .row("MSM")
    .row("WCW")
    .row("W W")
    .key("M", item("emergentengineering:double_compressed_marble"))
    .key("S", item("astralsorcery:blockblackmarble"))
    .key("W", item("emergentengineering:compressed_juniper_log"))
    .key("C", item("avaritia:double_compressed_crafting_table"))
    .register()

crafting.shapedBuilder()
    .name("luminous_crafting_table_ca")
    .output(item("astralsorcery:blockaltar"))
    .row("MSM")
    .row("WCW")
    .row("W W")
    .key("M", item("emergentengineering:compressed_marble"))
    .key("S", item("astralsorcery:blockblackmarble"))
    .key("W", item("extrautils2:ironwood_log"))
    .key("C", item("emergentengineering:crafting_catalyst"))
    .register()

crafting.shapedBuilder()
    .name("ferrous_juniper_3")
    .output(item("extrautils2:ironwood_sapling"))
    .row("III")
    .row("ISI")
    .row("III")
    .key("I", ore("blockIron"))
    .key("S", ore("treeSapling"))
    .register()

crafting.removeByOutput(item("extrautils2:resonator"))
crafting.shapedBuilder()
    .name("resonator_expensive")
    .output(item("extrautils2:resonator"))
    .row("RCR")
    .row("IEI")
    .row("III")
    .key("R", ore("blockRedstone"))
    .key("C", ore("blockCoal"))
    .key("I", ore("blockIron"))
    .key("E", item("extrautils2:ingredients"))
    .register()